__title__ = 'asyncrequests'
__description__ = 'Python Asynchronous HTTP client for asyncio.'
__version__ = '0.0.1'
__author__ = 'Sepehr Hamzehlouy'
__author_email__ = 's.hamzelooy@gmail.com'
__copyright__ = 'Copyright 2017 Sepehr Hamzehlouy'